version: 2.1

docker-image: &docker-image
    docker:
      - image: cimg/node:14.19.2

orbs:
  aws-cli: circleci/aws-cli@3.1.1

commands:
  persist_all_to_cwd:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .
  attach_workspace_at_cwd:
    steps:
      - attach_workspace:
          at: .
  install_pnpm:
    steps:
      - run:
          name: Install pnpm
          shell: /bin/bash
          command: |
            curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7.5.2
jobs:
  setup:
    <<: *docker-image
    steps:
      - checkout
      - install_pnpm
      - aws-cli/setup
      - run: aws codeartifact login --tool npm --repository ts --domain open-store
      - run: echo "always-auth=true" >> ~/.npmrc
      - run:
          name: Install dependencies
          shell: /bin/bash
          command: pnpm install
      - persist_all_to_cwd
  lint:
    <<: *docker-image
    steps:
      - attach_workspace_at_cwd
      - install_pnpm
      - run:
          name: Lint
          command: pnpm lint
  type-check:
    <<: *docker-image
    steps:
      - attach_workspace_at_cwd
      - install_pnpm
      - run:
          name: Type Check
          command: pnpm tsc --noEmit
  unit-test:
    <<: *docker-image
    steps:
      - attach_workspace_at_cwd
      - install_pnpm
      - run:
          name: Check formatting
          command: pnpm test 
workflows:
  pull_request:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - type-check:
          requires:
            - setup
      - unit-test:
          requires:
            - setup
